project:
  type: website
  output-dir: docs

website:
  title: "Probabilistic Models of Cognition"
  repo-url: "https://github.com/jpowerj/dsan5650"
  repo-actions: [source]
  repo-link-target: "_blank"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
      - text: "1. Introduction"
        href: ch01/index.qmd
      - text: "2. Generative Models"
        href: ch02/index.qmd
      - "---"
      - text: "<i class='bi bi-arrow-left'></i> DSAN 5650 Home"
        href: "https://jjacobs.me/dsan5650"

bibliography: ProbMods.bib

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    theme:
      light: [default, "./dsan-globals/jjquarto.scss"]
      dark: [darkly, "./dsan-globals/jjquarto.scss"]
    respect-user-color-scheme: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><script src='/sidebar.js'></script>"
    include-after-body:
      text: "<script src='/assets/js/webppl.min.js'></script><script src='/assets/js/webppl-viz.min.js'></script><script src='/assets/js/webppl-editor.min.js'></script><script src='/assets/js/paper-full.js'></script>"
  pdf:
    documentclass: scrreprt



