project:
  type: website
  output-dir: docs

website:
  title: "Probabilistic Models of Cognition"
  repo-url: "https://github.com/jpowerj/dsan5650"
  repo-actions: [source]
  repo-link-target: "_blank"
  page-navigation: true
  favicon: favicon.png
  sidebar:
    collapse-level: 1
    contents:
      - href: index.qmd
      - text: "1. Introduction"
        href: ch01/index.qmd
      - section: "2. Generative Models"
        href: ch02/index.qmd
        contents:
          - text: "Exercises"
            href: ch02/exercises.qmd
      - section: "3. Conditioning"
        href: ch03/index.qmd
        contents:
          - text: "Exercises"
            href: ch03/exercises.qmd
      - section: "4. Causal and Statistical Dependence"
        href: ch04/index.qmd
        contents:
          - text: "Exercises"
            href: ch04/exercises.qmd
      - section: "5. Conditional Dependence"
        href: ch05/index.qmd
        contents:
          - text: "Exercises"
            href: ch05/exercises.qmd
      - section: "6. Social Cognition"
        href: ch06/index.qmd
        contents:
          - text: "Exercises"
            href: ch06/exercises.qmd
      - section: "7. Interlude: Bayesian Data Analysis"
        href: ch07/index.qmd
        contents:
          - text: "Exercises"
            href: ch07/exercises.qmd
      - text: "8. Interlude: Algorithms for Inference"
        href: ch08/index.qmd
      - text: "9. Rational Process Models"
        href: ch09/index.qmd
      - text: "10. Learning as Conditional Inference"
        href: ch10/index.qmd
      - text: "11. Learning with a Language of Thought"
        href: ch11/index.qmd
      - text: "12. Hierarchical Models"
        href: ch12/index.qmd
      - text: "13. Occam's Razor"
        href: ch13/index.qmd
      - text: "14. Mixture Models"
        href: ch14/index.qmd
      - text: "15. Learning (Deep) Continuous Functions"
        href: ch15/index.qmd
      - text: "16. Appendix – JavaScript Basics"
        href: ch16/index.qmd
      - text: "17. Appendix – Useful Distributions"
        href: ch17/index.qmd
      - "---"
      - text: "<i class='bi bi-arrow-left'></i> DSAN 5650 Home"
        href: "https://jjacobs.me/dsan5650"

bibliography: ProbMods.bib
csl: chicago-17-no-url.csl

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    theme:
      light: [default, "./dsan-globals/jjquarto.scss"]
      dark: [darkly, "./dsan-globals/jjquarto.scss"]
    respect-user-color-scheme: true
    include-in-header:
      text: |
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script>
        <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'>
        <script src='/sidebar.js'></script>
        <link rel='preconnect' href='https://googleapis.com'>
        <link rel='preconnect' href='https://gstatic.com' crossorigin>
        <link href='https://googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet'>
        <link rel='stylesheet' href='/assets/css/webppl-editor.css'>
        <link rel='stylesheet' href='/assets/css/webppl-viz.css'>
        <script src='/assets/js/webppl.min.js'></script>
        <script src='/assets/js/webppl-viz.min.js'></script>
        <script src='/assets/js/webppl-editor.min.js' defer></script>
        <script src='/assets/js/paper-full.js'></script>
  pdf:
    documentclass: scrreprt



