---
title: "Exercises: Chapter 4"
chapter_num: 4
format:
  html:
    include-after-body:
      text: |
        <script src='../assets/js/box2d.js'></script>
        <script src='../assets/js/physics.js'></script>
        <script>
        document.addEventListener("DOMContentLoaded", () => {
          const chKey = 'ch04e'
          let jsBlocks = Array.from(
            document.querySelectorAll('pre')
          )
          jsBlocks
            .filter((elt) => !elt.classList.contains('default'))
            .forEach((elt, i) => {
              // Update cell content if in localStorage
              const lsKey = `${chKey}-cell-${i}`
              // Store the original (pre-localStorage) content
              const lsKeyOrig = `${chKey}-cell-${i}-orig`
              const origContent = elt.innerText
              localStorage.setItem(lsKeyOrig, origContent)
              const savedContent = localStorage.getItem(lsKey) || ''
              if (savedContent != '') {
                console.log(`Updating content to: ${savedContent}`)
                elt.innerHTML = `<pre>${savedContent}</pre>`
              }
              const result = editor.setup(elt, {
                language: 'webppl',
                lineNumbers: true,
              })
              // Listen for changes
              result.refs.editor.codeMirror.doc.on(
                "change",
                function(cm, changeObj) {
                  console.log(`Content changed in cell ${i}`)
                  const newVal = cm.getValue()
                  localStorage.setItem(lsKey, newVal)
                }
              )
            })
          // And... a "reset to original" button
          const codeBlocks = document.querySelectorAll('div[id^=cb]')
          codeBlocks.forEach((elt, i) => {
            console.log(elt.id)
            // Add a "restore previous content" popup
            const restoreContainer = document.createElement('div')
            restoreContainer.setAttribute('style','display: flex;')
            const restoreButton = document.createElement('button')
            restoreContainer.append(restoreButton)
            restoreButton.textContent = "Restore Original"
            restoreButton.setAttribute('style','margin-left: auto; font-size: 80%;')
            elt.style.marginTop = 0
            restoreButton.onclick = function() {
              console.log(`restoring ${i}`)
              const cmObj = elt.firstChild.firstChild.firstChild.children[1].CodeMirror
              console.log(cmObj)
              // Use setValue to update the content
              const origValKey = `${chKey}-cell-${i}-orig`
              const origVal = localStorage.getItem(origValKey)
              cmObj.setValue(origVal)
            }
            // Add it before the current one
            elt.before(restoreContainer)
            const eltButtons = elt.querySelectorAll('button')
            console.log(eltButtons)
          })
        })
        </script>
  pdf: default
---

## Exercise 4.1: Causal and Statistical Dependency

For each of the following programs:

* Draw the dependency diagram as a Bayes Net. If you don't have software on your computer for doing this, Google Docs has a decent interface for creating drawings.
* Use informal evaluation order reasoning and the intervention method to determine causal dependency between `A` and `B`.
* Use conditioning to determine whether `A` and `B` are statistically dependent.

### Question 4.1.1

```{.js}
var A = flip()
var B = flip()
var C = flip(A && B ? .8 : .5)
```

### Question 4.1.2

```{.js}
var A = flip()
var B = flip(A ? .9 : .2)
var C = flip(B ? .7 : .1)
```

### Question 4.1.3

```{.js}
var a = flip()
var b = flip(a ? .9 : .2)
var c = flip(a ? .7 : .1)
```

### Question 4.1.4

```{.js}
var A = flip(.6);
var C = flip(.1);
var Z = flip() ? A : C;
var B = Z ? 'foo' : 'bar';
```

### Question 4.1.5

```{.js}
var examFairPrior = Bernoulli({p: .8})
var doesHomeworkPrior = Bernoulli({p: .8})
var examFair = mem(
  function(exam) {
    return sample(examFairPrior)
  }
)
var doesHomework = mem(
  function(student) {
    return sample(doesHomeworkPrior)
  }
)

var pass = function(student, exam) {
  return flip(
    examFair(exam)
      ? (doesHomework(student) ? .9 : .5)
      : (doesHomework(student) ? .2 : .1)
  )
}
var A = pass('alice', 'historyExam');
var B = pass('bob', 'historyExam');
```

## Exercise 4.2: Probabilistic Programs Without Corresponding Graphical Models

As the end of the chapter mentions, some probabilistic programs do not have corresponding graphical models. This includes programs with recursion. The example below is an example of a recursive probabilistic program:

```{.js}
// Compute total rainfall over the
// course of a storm
var totalRain = function() {
  // Amount of rainfall today
  var dailyRainfall = sample(
    Gaussian({
      mu: 5,
      sigma: 1
    })
  )
  // If it rained a lot today,
  // the storm is likely to continue
  if (
    (dailyRainfall > 6 && flip(0.8))
    || flip(0.3)
  ) {
    return dailyRainfall + totalRain()
  } else {
    return dailyRainfall
  }
}

viz(
  Infer({
    model: totalRain,
    method: "forward"
  })
)
```

### Question 4.2.1

Write another recursive probabilistic program to model some real-world phenomenon below:

```{.js}
// Your code here

```
